### ISSUE TITLE
java.lang.VerifyError: Incompatible argument to function

### ISSUE THREAD

**Issue by blakeelias** [StuyPulse/VIRSYSJ#1]
joebot.test throws the following error when constructing the OI:

Testcase: edu.stuy.commands.DriveManualJoystickControlTest:
Caused an ERROR
java.lang.VerifyError: (class: edu/stuy/OI, method: <init> signature:
()V) Incompatible argument to function
        at edu.stuy.commands.base.CommandBase.init(CommandBase.java:41)
        at edu.stuy.JoeBot.robotInit(JoeBot.java:44)
        at edu.stuy.commands.DriveManualJoystickControlTest.setUpClass(DriveManualJoystickControlTest.java:32)

**Comment by blakeelias** [comment]
Can be averted by commenting out the following lines in joebot's edu/stuy/OI.java:

import edu.wpi.first.wpilibj.buttons.*;

new JoystickButton(leftStick, 1).whileHeld(new ShooterShoot());
new JoystickButton(leftStick, 2).whenPressed(new DrivetrainSetGear(false));
new JoystickButton(rightStick, 2).whenPressed(new DrivetrainSetGear(true));

VerifyErrors can arise when a program calls classes or methods that are not found in its runtime classpath (or methods with different signatures), but everything called here exists in VIRSYSJ.  I suspect it has something to do with JoystickButton.
